// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: f99681fc3772d03dae95f7ec80d2d845e46ecfbf22dbb019065dcba1a666cb8a

import type { ObjectReference, ListMeta } from './base.js';

export type User = ObjectReference & {
  email: string;
  name: string;
  username: string;
};

export type UserList = ListMeta & {
  items: User[];
};

export type UserCreateRequest = {
  email?: string;
  name?: string;
  username: string;
};

export type UserPatchRequest = {
};


export type UserActivityStats = {
  active_daily: UserDailyCount[];
  active_last_30_days: number;
  active_last_7_days: number;
  registered_last_30_days: number;
  registered_last_7_days: number;
  registration_daily: UserDailyCount[];
  total_registered: number;
};



export type UserDailyCount = {
  count: number;
  date: string;
};



export class UserBuilder {
  private data: Record<string, unknown> = {};


  email(value: string): this {
    this.data['email'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  username(value: string): this {
    this.data['username'] = value;
    return this;
  }

  build(): UserCreateRequest {
    if (!this.data['username']) {
      throw new Error('username is required');
    }
    return this.data as UserCreateRequest;
  }
}

export class UserPatchBuilder {
  private data: Record<string, unknown> = {};


  build(): UserPatchRequest {
    return this.data as UserPatchRequest;
  }
}
